Repository mineraux/make-bench-great-again, pull requests merged in 2019-04, with the labels that each got.

#1 Structure de base de l'API
  api/.gitignore
  api/.gitkeep
  api/app.js
  api/graphql/resolvers/benchList.js
  api/graphql/resolvers/index.js
  api/graphql/schema/index.graphql
  api/models/bench.js
  api/nodemon.json
  api/package.json
  api/yarn.lock
Labels: dev, enhancement

#2 Amélioration de l'API
  api/graphql/resolvers/benchList.js
  api/graphql/resolvers/index.js
  api/graphql/resolvers/petitionList.js
  api/graphql/schema/index.graphql
  api/models/bench.js
  api/models/petition.js
Labels: dev, enhancement

#3 Link the API to MobX
  client/package.json
  client/src/@types/index.d.ts
  client/src/ApiClient/ApiClient.ts
  client/src/App.tsx
  client/src/assets/images/bug.svg
  client/src/assets/styles/global.scss
  client/src/clients/ApiClient.ts
  client/src/components/debug/DebugButton.tsx
  client/src/components/debug/DebugPanel.tsx
  client/src/components/debug/debugButton.scss
  client/src/components/debug/debugPanel.scss
  client/src/store/DebugStore.ts
  client/src/store/Store.ts
  client/yarn.lock
Labels: dev, enhancement

#4 :sparkles: add Router and routes transition
  client/package.json
  client/src/App.tsx
  client/src/assets/styles/index.scss
  client/src/components/Nav/Nav.tsx
  client/src/components/Nav/nav.scss
  client/src/index.tsx
  client/src/pages/Home/Home.tsx
  client/src/pages/Map/Map.tsx
  client/yarn.lock
Labels: enhancement

#5 Mapbox, geolocate and directions
  .gitignore
  api/app.js
  api/nodemon.json
  client/package.json
  client/src/@types/index.d.ts
  client/src/@types/mapbox__mapbox-gl-direction/index.d.ts
  client/src/ApiClient/ApiClient.ts
  client/src/App.tsx
  client/src/clients/ApiClient.ts
  client/src/components/debug/DebugPanel.tsx
  client/src/components/debug/debugPanel.scss
  client/src/components/map/ProtoMap.tsx
  client/src/components/map/map.scss
  client/src/pages/Map/Map.tsx
  client/src/store/Store.ts
  client/tsconfig.json
  client/yarn.lock
Labels: enhancement

#7 Closes: #6 - Amélioration de la map
  client/package.json
  client/src/@types/index.d.ts
  client/src/components/map/MapManager.ts
  client/src/components/map/ProtoMap.tsx
  client/src/store/Store.ts
  client/yarn.lock
Labels: enhancement, map

#11 Close: #9 - Amélioration de l'API et de la récupération des datas côté client - Nouvelle méthode sur l'API et refacto d'une partie du store
  api/graphql/resolvers/benchList.js
  api/graphql/schema/index.graphql
  client/src/@types/index.d.ts
  client/src/ApiClient/ApiClient.ts
  client/src/components/debug/DebugPanel.tsx
  client/src/components/map/MapManager.ts
  client/src/components/map/ProtoMap.tsx
  client/src/store/Store.ts
Labels: API MBGA, enhancement

#15 Feature/twitter api
  api/.env
  api/.gitignore
  api/app.js
  api/package.json
  api/yarn.lock
  client/.env
  client/package.json
  client/src/@types/index.d.ts
  client/src/App.tsx
  client/src/components/Nav/Nav.tsx
  client/src/config/config.ts
  client/src/pages/Home/Home.tsx
  client/src/pages/Map/Map.tsx
  client/src/pages/Twitter/Twitter.tsx
  client/src/pages/Twitter/twitter.scss
  client/src/pages/types.ts
  client/yarn.lock
Labels: API Twitter

#17 Interface d'admin CRUD pour les installations
  api/graphql/resolvers/benchList.js
  api/graphql/schema/index.graphql
  client/src/@types/index.d.ts
  client/src/ApiClient/ApiClient.ts
  client/src/components/debug/DebugPanel.tsx
  client/src/config/config.ts
  client/src/pages/Admin/Admin.tsx
  client/src/pages/Admin/admin.scss
  client/src/store/Store.ts
Labels: API MBGA, enhancement
