Repository mineraux/make-bench-great-again, pull requests merged in 2019-06, with the labels that each got.

#144 create Programmation page + Installationthumbnail
  client/src/components/InstallationThumbnail/InstallationThumbnail.tsx
  client/src/components/InstallationThumbnail/installation-thumbnail.scss
  client/src/config/config.ts
  client/src/pages/Menu/Menu.tsx
  client/src/pages/Menu/menu.scss
  client/src/pages/Programmation/Programmation.tsx
  client/src/pages/Programmation/Transition.tsx
  client/src/pages/Programmation/programmation.scss
Labels: component, ui

#146 AudioPlayer : fix audio currentTime update
  client/src/components/AudioPlayer/AudioPlayer.tsx
  client/src/pages/Components/Components.tsx
Labels: fix

#149 Installation page : split unlocked / locked in different folders
  client/src/pages/Installation/Installation.tsx
  client/src/pages/Installation/locked/InstallationLocked.tsx
  client/src/pages/Installation/locked/installation-locked.scss
  client/src/pages/Installation/unlocked/InstallationUnlocked.tsx
  client/src/pages/Installation/unlocked/ScrollMagicController.ts
  client/src/pages/Installation/unlocked/installation-unlocked.scss
Labels: refacto

#151 Sauvegarde de la progression de l'utilisateur
  client/src/components/map/ProtoMap.tsx
  client/src/pages/Installation/Installation.tsx
  client/src/store/InstallationStore.ts
Labels: enhancement

#163 Refacto page Installation
  client/src/components/SpriteAnimation/SpriteAnimation.tsx
  client/src/pages/Installation/unlocked/InstallationUnlocked.tsx
  client/src/pages/Installation/unlocked/ScrollMagicController.ts
  client/src/pages/Installation/unlocked/installation-unlocked.scss
Labels: refacto, ui

#165 Feature/finish animation svg
  client/src/config/config.ts
  client/src/pages/Finish/Finish.tsx
  client/src/pages/Finish/background.svg
  client/src/pages/Finish/finish.scss
  client/src/pages/Finish/progress.svg
Labels: ui

#164 Mise à jour de la page 'Success'
  client/src/components/Header/header.scss
  client/src/pages/Success/Success.tsx
  client/src/pages/Success/Transition.tsx
  client/src/pages/Success/success.scss
Labels: enhancement, ui

#168 Update menu animation
  client/src/App.tsx
  client/src/components/BurgerButton/BurgerButton.tsx
  client/src/components/Header/Header.tsx
  client/src/components/MapButton/MapButton.tsx
  client/src/components/MapButton/mapButton.scss
  client/src/pages/About/About.tsx
  client/src/pages/Components/Components.tsx
  client/src/pages/Installation/locked/InstallationLocked.tsx
  client/src/pages/Installation/unlocked/InstallationUnlocked.tsx
  client/src/pages/Map/Map.tsx
  client/src/pages/Menu/Transition.tsx
  client/src/pages/Menu/menu.scss
  client/src/store/NavigationStore.ts
Labels: ui

#169 Mise à jour de la page d'installation bloquée
  client/src/assets/images/banc_metro_01.png
  client/src/components/InformationsPanel/InformationsPanel.tsx
  client/src/components/map/ProtoMap.tsx
  client/src/pages/Installation/locked/InstallationLocked.tsx
  client/src/pages/Installation/locked/ScrollMagicController.ts
  client/src/pages/Installation/locked/installation-locked.scss
  client/src/pages/Installation/locked/progress.svg
  client/src/store/InstallationStore.ts
  client/src/store/MapStore.ts
  client/src/utils/hooks.ts
  client/src/utils/index.ts
Labels: enhancement, map, ui

#170 Mise à jour des styles de la page Map
  client/src/assets/styles/global.scss
  client/src/components/InformationsPanel/InformationsPanel.tsx
  client/src/components/InformationsPanel/informationsPanel.scss
  client/src/components/map/ProtoMap.tsx
  client/src/components/map/mapgl.scss
  client/src/pages/Map/Transition.tsx
  client/src/store/MapStore.ts
  client/src/utils/map.ts
Labels: enhancement, map, refacto, ui

#175 Update/home page
  client/src/pages/Home/Home.tsx
  client/src/pages/Home/home.scss
Labels: refacto, ui

#181 Dynamisation de la page Finish
  client/src/pages/Finish/Finish.tsx
Labels: refacto, ui

#176 Mise à jour de l'animation de contenu bloqué & refacto du template
  client/src/@types/index.d.ts
  client/src/assets/images/banc_metro_01.png
  client/src/components/InformationsPanel/InformationsPanel.tsx
  client/src/components/InformationsPanel/informationsPanel.scss
  client/src/components/map/ProtoMap.tsx
  client/src/components/map/mapgl.scss
  client/src/pages/Admin/Admin.tsx
  client/src/pages/Installation/locked/InstallationLocked.tsx
  client/src/pages/Installation/locked/ScrollMagicController.ts
  client/src/pages/Installation/locked/installation-locked.scss
  client/src/pages/Map/Transition.tsx
  client/src/store/InstallationStore.ts
  client/src/store/MapStore.ts
  client/src/store/NavigationStore.ts
  client/src/utils/hooks.ts
  client/src/utils/index.ts
  client/src/utils/map.ts
Labels: refacto, ui

#183 Fix/general layout
  client/src/components/InformationsPanel/InformationsPanel.tsx
  client/src/components/map/ProtoMap.tsx
  client/src/pages/Finish/Finish.tsx
  client/src/pages/Home/Home.tsx
  client/src/pages/Home/home.scss
  client/src/pages/Installation/locked/InstallationLocked.tsx
  client/src/store/InstallationStore.ts
Labels: map, refacto, ui

#184 Update/general layout
  client/package.json
  client/src/components/InformationsPanel/InformationsPanel.tsx
  client/src/components/TutoTwitter/TutoTwitter.tsx
  client/src/components/TutoTwitter/tuto-twitter.scss
  client/src/pages/Home/Home.tsx
  client/src/pages/Home/ScrollMagicController.ts
  client/src/pages/Home/home.scss
  client/src/pages/Installation/unlocked/ScrollMagicController.ts
  client/yarn.lock
Labels: refacto, ui

#187 Home : fix scrollmagic + improve animations
  client/src/components/Header/Header.tsx
  client/src/components/Header/header.scss
  client/src/pages/Home/Home.tsx
  client/src/pages/Home/ScrollMagicController.ts
  client/src/pages/Home/Transition.tsx
  client/src/pages/Home/home.scss
Labels: fix

#189 Update/scroll indication
  client/src/App.tsx
  client/src/assets/styles/app.scss
  client/src/components/ScrollIndication/ScrollIndication.tsx
  client/src/components/ScrollIndication/scroll-indication.scss
  client/src/components/SplashscreenAnimation/SplashscreenAnimation.tsx
  client/src/components/SplashscreenAnimation/splashscreen-animation.scss
  client/src/config/config.ts
  client/src/pages/Home/Home.tsx
  client/src/pages/Home/ScrollMagicController.ts
  client/src/pages/Home/home.scss
  client/src/pages/Installation/Installation.tsx
  client/src/pages/Installation/Transition.tsx
  client/src/pages/Installation/locked/InstallationLocked.tsx
  client/src/pages/Installation/locked/ScrollMagicController.ts
  client/src/pages/Installation/locked/Transition.tsx
  client/src/pages/Installation/unlocked/InstallationUnlocked.tsx
  client/src/pages/Installation/unlocked/ScrollMagicController.ts
  client/src/pages/Installation/unlocked/Transition.tsx
  client/src/store/NavigationStore.ts
  client/src/store/index.ts
Labels: component, enhancement, ui

#190 Fix/general layout
  api/app.js
  client/public/assets/images/installations/en_suspens_locked.png
  client/public/assets/images/installations/en_suspens_unlocked.png
  client/public/assets/images/installations/exedros_locked.png
  client/public/assets/images/installations/exedros_unlocked.png
  client/public/assets/images/installations/ligne_locked.png
  client/public/assets/images/installations/mi-lune_locked.png
  client/public/assets/images/installations/raccord_locked.png
  client/public/assets/images/installations/vague_locked.png
  client/public/assets/images/installations/vague_unlocked.png
  client/src/@types/index.d.ts
  client/src/assets/images/banc_metro_01.png
  client/src/assets/images/bench.png
  client/src/components/AudioPlayer/audio-player.scss
  client/src/components/Button/button.scss
  client/src/components/InformationsPanel/informationsPanel.scss
  client/src/components/InstallationThumbnail/InstallationThumbnail.tsx
  client/src/components/InstallationThumbnail/installation-thumbnail.scss
  client/src/components/Modal/modal.scss
  client/src/components/TutoTwitter/TutoTwitter.tsx
  client/src/components/TutoTwitter/tuto-twitter.scss
  client/src/components/TwitterGallery/TwitterGallery.tsx
  client/src/components/map/mapgl.scss
  client/src/pages/Installation/unlocked/InstallationUnlocked.tsx
  client/src/pages/Installation/unlocked/ScrollMagicController.ts
  client/src/pages/Installation/unlocked/Transition.tsx
  client/src/pages/Installation/unlocked/installation-unlocked.scss
  client/src/pages/Map/Map.tsx
  client/src/pages/Programmation/Programmation.tsx
  client/src/pages/Success/Success.tsx
  client/src/pages/Success/success.scss
  client/src/store/InstallationStore.ts
Labels: refacto, ui

#197 TwitterGallery : get media url with https
  client/src/components/TwitterGallery/TwitterGallery.tsx
Labels: API Twitter

#200 Success page : transition
  client/src/pages/Installation/unlocked/installation-unlocked.scss
  client/src/pages/Success/Transition.tsx
  client/src/pages/Success/success.scss
Labels: refacto, ui

#199 Fix bug installationLocked
  client/src/pages/Installation/locked/InstallationLocked.tsx
Labels: refacto

#198 Added animation on close modal
  client/src/components/map/ProtoMap.tsx
Labels: ui

#202 TwitterGallery : control tweet live reload
  client/src/components/TwitterGallery/TwitterGallery.tsx
  client/src/pages/Installation/unlocked/InstallationUnlocked.tsx
  client/src/pages/Installation/unlocked/ScrollMagicController.ts
  client/src/store/ScrollMagicStore.ts
Labels: API Twitter

#203 TutoTwitter : fix video play
  client/src/components/TutoTwitter/TutoTwitter.tsx
Labels: fix

#205 InstallationUnlocked : fix testimony text fade in
  client/src/pages/Installation/unlocked/ScrollMagicController.ts
  client/src/pages/Installation/unlocked/installation-unlocked.scss
Labels: fix, ui

#204 InstallationUnlocked : MapButton dynamic theme
  client/src/components/MapButton/MapButton.tsx
  client/src/components/MapButton/mapButton.scss
  client/src/pages/Installation/unlocked/InstallationUnlocked.tsx
  client/src/pages/Installation/unlocked/ScrollMagicController.ts
Labels: ui
