Repository mineraux/make-bench-great-again, pull requests merged in 2019-05, with the labels that each got.

#22 Fix/prettier
  client/package.json
  client/src/@types/index.d.ts
  client/src/ApiClient/ApiClient.ts
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/assets/styles/global.scss
  client/src/components/Nav/Nav.tsx
  client/src/components/Nav/nav.scss
  client/src/components/debug/DebugButton.tsx
  client/src/components/debug/DebugPanel.tsx
  client/src/components/debug/debugButton.scss
  client/src/components/debug/debugPanel.scss
  client/src/components/map/InformationsPanel.tsx
  client/src/components/map/ProtoMap.tsx
  client/src/components/map/map.scss
  client/src/config/config.ts
  client/src/index.tsx
  client/src/pages/Admin/Admin.tsx
  client/src/pages/Admin/admin.scss
  client/src/pages/Bench/Bench.tsx
  client/src/pages/Home/Home.tsx
  client/src/pages/Map/Map.tsx
  client/src/pages/Twitter/Twitter.tsx
  client/src/pages/Twitter/twitter.scss
  client/src/pages/types.ts
  client/src/store/DebugStore.ts
  client/src/store/Store.ts
  client/src/utils/map.ts
  client/yarn.lock
Labels: fix

#23 Refacto de l'API client
  client/src/ApiClient/ApiClient.ts
  client/src/components/debug/DebugPanel.tsx
Labels: API MBGA, refacto

#27 Update/page transition
  client/src/ApiClient/ApiClient.ts
  client/src/App.tsx
  client/src/components/debug/DebugPanel.tsx
  client/src/pages/Admin/Admin.tsx
  client/src/pages/Admin/Transition.tsx
  client/src/pages/Bench/Bench.tsx
  client/src/pages/Bench/Transition.tsx
  client/src/pages/Home/Home.tsx
  client/src/pages/Home/Transition.tsx
  client/src/pages/Map/Map.tsx
  client/src/pages/Map/Transition.tsx
  client/src/pages/Twitter/Transition.tsx
  client/src/pages/Twitter/Twitter.tsx
  client/src/store/PageStore.ts
Labels: refacto, ui

#28 Update/mbga api
  api/app.js
  api/graphql/resolvers/benchList.js
  api/graphql/resolvers/petitionList.js
  api/graphql/schema/index.graphql
  api/models/bench.js
  api/models/petition.js
  client/src/@types/index.d.ts
  client/src/ApiClient/ApiClient.ts
  client/src/pages/Admin/Admin.tsx
Labels: API MBGA, enhancement, refacto

#31 Feature/fonts
  client/src/assets/fonts/Avenir/Medium/AvenirLTStd-Medium.eot
  client/src/assets/fonts/Avenir/Medium/AvenirLTStd-Medium.svg
  client/src/assets/fonts/Avenir/Medium/AvenirLTStd-Medium.ttf
  client/src/assets/fonts/Avenir/Medium/AvenirLTStd-Medium.woff
  client/src/assets/fonts/Faune/Black/Faune-Text_Black.eot
  client/src/assets/fonts/Faune/Black/Faune-Text_Black.svg
  client/src/assets/fonts/Faune/Black/Faune-Text_Black.ttf
  client/src/assets/fonts/Faune/Black/Faune-Text_Black.woff
  client/src/assets/fonts/Faune/Black/Faune-Text_Black.woff2
  client/src/assets/fonts/Faune/Bold/Faune-Text_Bold.eot
  client/src/assets/fonts/Faune/Bold/Faune-Text_Bold.svg
  client/src/assets/fonts/Faune/Bold/Faune-Text_Bold.ttf
  client/src/assets/fonts/Faune/Bold/Faune-Text_Bold.woff
  client/src/assets/fonts/Faune/Bold/Faune-Text_Bold.woff2
  client/src/assets/fonts/Faune/BoldItalic/Faune-Text_Bold_Italic.eot
  client/src/assets/fonts/Faune/BoldItalic/Faune-Text_Bold_Italic.svg
  client/src/assets/fonts/Faune/BoldItalic/Faune-Text_Bold_Italic.ttf
  client/src/assets/fonts/Faune/BoldItalic/Faune-Text_Bold_Italic.woff
  client/src/assets/fonts/Faune/BoldItalic/Faune-Text_Bold_Italic.woff2
  client/src/assets/fonts/Faune/Italic/Faune-Text_Italic.eot
  client/src/assets/fonts/Faune/Italic/Faune-Text_Italic.svg
  client/src/assets/fonts/Faune/Italic/Faune-Text_Italic.ttf
  client/src/assets/fonts/Faune/Italic/Faune-Text_Italic.woff
  client/src/assets/fonts/Faune/Italic/Faune-Text_Italic.woff2
  client/src/assets/fonts/Faune/Regular/Faune-Text_Regular.eot
  client/src/assets/fonts/Faune/Regular/Faune-Text_Regular.svg
  client/src/assets/fonts/Faune/Regular/Faune-Text_Regular.ttf
  client/src/assets/fonts/Faune/Regular/Faune-Text_Regular.woff
  client/src/assets/fonts/Faune/Regular/Faune-Text_Regular.woff2
  client/src/assets/fonts/Faune/Thin/Faune-Text_Thin.eot
  client/src/assets/fonts/Faune/Thin/Faune-Text_Thin.svg
  client/src/assets/fonts/Faune/Thin/Faune-Text_Thin.ttf
  client/src/assets/fonts/Faune/Thin/Faune-Text_Thin.woff
  client/src/assets/fonts/Faune/Thin/Faune-Text_Thin.woff2
  client/src/assets/fonts/Infini/Gras/infini-gras.eot
  client/src/assets/fonts/Infini/Gras/infini-gras.otf
  client/src/assets/fonts/Infini/Gras/infini-gras.svg
  client/src/assets/fonts/Infini/Gras/infini-gras.ttf
  client/src/assets/fonts/Infini/Gras/infini-gras.woff
  client/src/assets/fonts/Infini/Italique/infini-italique.eot
  client/src/assets/fonts/Infini/Italique/infini-italique.otf
  client/src/assets/fonts/Infini/Italique/infini-italique.svg
  client/src/assets/fonts/Infini/Italique/infini-italique.ttf
  client/src/assets/fonts/Infini/Italique/infini-italique.woff
  client/src/assets/fonts/Infini/Romain/infini-romain.eot
  client/src/assets/fonts/Infini/Romain/infini-romain.otf
  client/src/assets/fonts/Infini/Romain/infini-romain.svg
  client/src/assets/fonts/Infini/Romain/infini-romain.ttf
  client/src/assets/fonts/Infini/Romain/infini-romain.woff
  client/src/assets/styles/fonts.scss
  client/src/assets/styles/global.scss
  client/src/assets/styles/index.scss
  client/src/assets/styles/variables.scss
Labels: ui

#34 Feature/button
  client/package.json
  client/src/assets/styles/variables.scss
  client/src/components/Button/Button.tsx
  client/src/components/Button/button.scss
  client/src/config/config.ts
  client/src/pages/Components/Components.tsx
  client/src/pages/Components/Transition.tsx
  client/yarn.lock
Labels: component, ui

#37 Feature/tslint
  client/package.json
  client/src/@types/index.d.ts
  client/src/ApiClient/ApiClient.ts
  client/src/App.tsx
  client/src/components/debug/DebugPanel.tsx
  client/src/components/map/DirectionsController.ts
  client/src/components/map/InformationsPanel.tsx
  client/src/components/map/MapController.ts
  client/src/components/map/ProtoMap.tsx
  client/src/pages/Admin/Admin.tsx
  client/src/pages/Admin/Transition.tsx
  client/src/pages/Bench/Bench.tsx
  client/src/pages/Bench/Transition.tsx
  client/src/pages/Components/Components.tsx
  client/src/pages/Components/Transition.tsx
  client/src/pages/Home/Transition.tsx
  client/src/pages/Map/Transition.tsx
  client/src/pages/Twitter/Transition.tsx
  client/src/pages/Twitter/Twitter.tsx
  client/src/store/PageStore.ts
  client/tslint.json
Labels: enhancement

#39 Feature/countdown
  client/src/components/Countdown/Countdown.tsx
  client/src/components/Countdown/countdown.scss
  client/src/components/Nav/nav.scss
  client/src/pages/Components/Components.tsx
Labels: component

#40 Amélioration du panneau d'informations
  client/src/assets/images/close_ico.svg
  client/src/components/Button/button.scss
  client/src/components/InformationsPanel/InformationsPanel.tsx
  client/src/components/InformationsPanel/informationsPanel.scss
  client/src/components/Nav/nav.scss
  client/src/components/map/DirectionsController.ts
  client/src/components/map/InformationsPanel.tsx
  client/src/components/map/ProtoMap.tsx
  client/src/components/map/map.scss
  client/src/pages/Map/Map.tsx
  client/src/store/Store.ts
Labels: component, enhancement, ui

#42 Composant de modal
  client/src/components/Button/button.scss
  client/src/components/Modal/Modal.tsx
  client/src/components/Modal/modal.scss
  client/src/components/map/ProtoMap.tsx
  client/src/components/map/mapgl.scss
  client/src/pages/Components/Components.tsx
Labels: component, enhancement, map, ui

#45 :recycle: :art: Updated props naming & show/hide modal with state
  client/src/components/Modal/Modal.tsx
  client/src/components/map/ProtoMap.tsx
  client/src/pages/Components/Components.tsx
Labels: component, fix, refacto

#47 :sparkles: #46 add BurgerButton component
  client/src/components/BurgerButton/BurgerButton.tsx
  client/src/components/BurgerButton/burger-button.scss
  client/src/pages/Components/Components.tsx
  client/src/store/PageStore.ts
Labels: component, ui

#51 :recycle: #50 refactor stores exports and naming
  client/src/App.tsx
  client/src/components/BurgerButton/BurgerButton.tsx
  client/src/components/debug/DebugButton.tsx
  client/src/components/debug/DebugPanel.tsx
  client/src/components/map/ProtoMap.tsx
  client/src/pages/Admin/Transition.tsx
  client/src/pages/Bench/Bench.tsx
  client/src/pages/Components/Transition.tsx
  client/src/pages/Home/Transition.tsx
  client/src/pages/Map/Transition.tsx
  client/src/pages/Twitter/Transition.tsx
  client/src/store/BenchStore.ts
  client/src/store/NavigationStore.ts
  client/src/store/index.ts
Labels: refacto

#53 Détection de la proximité avec une installation et mise à jour du trajet
  client/src/components/map/ProtoMap.tsx
Labels: enhancement, map

#54 Renommage des "Bench"
  api/graphql/resolvers/benchList.js
  api/graphql/resolvers/index.js
  api/graphql/resolvers/installationList.js
  api/graphql/resolvers/petitionList.js
  api/graphql/schema/index.graphql
  api/models/installation.js
  api/models/petition.js
  client/src/@types/index.d.ts
  client/src/ApiClient/ApiClient.ts
  client/src/components/InformationsPanel/InformationsPanel.tsx
  client/src/components/InformationsPanel/informationsPanel.scss
  client/src/components/debug/DebugPanel.tsx
  client/src/components/map/MapController.ts
  client/src/components/map/ProtoMap.tsx
  client/src/config/config.ts
  client/src/pages/Admin/Admin.tsx
  client/src/pages/Bench/Bench.tsx
  client/src/pages/Installation/Installation.tsx
  client/src/pages/Installation/Transition.tsx
  client/src/store/InstallationStore.ts
  client/src/store/index.ts
Labels: API MBGA, refacto

#56 add ProgressBar component + ScrollIndication component
  client/src/components/Header/Header.tsx
  client/src/components/Header/header.scss
  client/src/components/ProgressBar/ProgressBar.tsx
  client/src/components/ProgressBar/progress-bar.scss
  client/src/components/ScrollIndication/ScrollIndication.tsx
  client/src/components/ScrollIndication/arrow.svg
  client/src/components/ScrollIndication/scroll-indication.scss
  client/src/pages/Components/Components.tsx
  client/src/pages/Components/components.scss
  client/src/store/NavigationStore.ts
Labels: component, ui

#63 page home + header + nav
  client/public/index.html
  client/src/App.tsx
  client/src/assets/styles/app.scss
  client/src/assets/styles/index.scss
  client/src/assets/styles/variables.scss
  client/src/components/Button/Button.tsx
  client/src/components/Header/header.scss
  client/src/components/Nav/Nav.tsx
  client/src/components/Nav/nav.scss
  client/src/pages/Home/Home.tsx
  client/src/pages/Home/home.scss
  client/src/store/NavigationStore.ts
  client/src/utils/index.ts
Labels: component, ui

#60 Style map et blur
  client/src/components/map/MapController.ts
  client/src/components/map/ProtoMap.tsx
  client/src/components/map/mapgl.scss
Labels: enhancement, map, ui

#66 Feature/https
  api/.env
  api/.gitignore
  api/app.js
  client/package.json
Labels: enhancement

#70 component/TwitterThumbnail
  client/src/components/TwitterThumbnail/TwitterThumbnail.tsx
  client/src/components/TwitterThumbnail/heart.svg
  client/src/components/TwitterThumbnail/twitter-thumbnail.scss
  client/src/pages/Twitter/Twitter.tsx
  client/src/pages/Twitter/twitter.scss
Labels: component, ui

#71 Component/twitter gallery
  api/app.js
  client/src/assets/styles/variables.scss
  client/src/components/Header/header.scss
  client/src/components/TwitterDebug/TwitterDebug.tsx
  client/src/components/TwitterDebug/twitter-debug.scss
  client/src/components/TwitterGallery/TwitterGallery.tsx
  client/src/components/TwitterGallery/twitter-gallery.scss
  client/src/components/TwitterGallery/twitter.svg
  client/src/components/TwitterThumbnail/TwitterThumbnail.tsx
  client/src/components/TwitterThumbnail/twitter-thumbnail.scss
  client/src/pages/Twitter/Twitter.tsx
  client/src/pages/Twitter/twitter.scss
Labels: API Twitter, component, enhancement, ui

#73 refacto page and transition component
  client/src/config/config.ts
  client/src/pages/Admin/Admin.tsx
  client/src/pages/Admin/Transition.tsx
  client/src/pages/Components/Components.tsx
  client/src/pages/Components/Transition.tsx
  client/src/pages/Home/Home.tsx
  client/src/pages/Home/Transition.tsx
  client/src/pages/Installation/Installation.tsx
  client/src/pages/Installation/Transition.tsx
  client/src/pages/Map/Map.tsx
  client/src/pages/Map/Transition.tsx
  client/src/pages/Twitter/Transition.tsx
  client/src/pages/Twitter/Twitter.tsx
  client/src/pages/types.ts
Labels: refacto

#74 Update/installation page
  client/config/env.js
  client/config/jest/cssTransform.js
  client/config/jest/fileTransform.js
  client/config/paths.js
  client/config/webpack.config.js
  client/config/webpackDevServer.config.js
  client/package.json
  client/scripts/build.js
  client/scripts/start.js
  client/scripts/test.js
  client/src/App.tsx
  client/src/assets/images/bench.png
  client/src/assets/images/dummy_player.png
  client/src/assets/styles/variables.scss
  client/src/pages/Installation/Installation.tsx
  client/src/pages/Installation/ScrollMagicController.ts
  client/src/pages/Installation/installation.scss
  client/src/react-app-env.d.ts
  client/yarn.lock
Labels: enhancement, refacto, ui

#83 Component/sprite animation
  client/package.json
  client/src/components/SpriteAnimation/SpriteAnimation.tsx
  client/src/components/SpriteAnimation/animations/banc-metro.png
  client/src/components/SpriteAnimation/animations/index.ts
  client/src/components/SpriteAnimation/sprite-animation.scss
  client/src/pages/Components/Components.tsx
  client/src/pages/Components/components.scss
  client/yarn.lock
Labels: component

#85 Update/installation page
  client/package.json
  client/src/App.tsx
  client/src/assets/images/ico_twitter.svg
  client/src/components/Button/Button.tsx
  client/src/components/Button/button.scss
  client/src/components/MapButton/MapButton.tsx
  client/src/components/MapButton/mapButton.scss
  client/src/components/MapButton/marker.svg
  client/src/components/Modal/modal.scss
  client/src/components/debug/debugPanel.scss
  client/src/components/map/DirectionsStyles.ts
  client/src/pages/Components/Components.tsx
  client/src/pages/Installation/Installation.tsx
  client/src/pages/Installation/ScrollMagicController.ts
  client/src/pages/Installation/Transition.tsx
  client/src/pages/Installation/installation.scss
  client/src/pages/Map/Map.tsx
  client/src/pages/types.ts
  client/src/store/NavigationStore.ts
Labels: component, enhancement, map, ui

#88 Update/store installations
  client/src/@types/index.d.ts
  client/src/components/map/MapController.ts
  client/src/pages/Components/Components.tsx
  client/src/pages/Installation/Installation.tsx
  client/src/store/InstallationStore.ts
Labels: enhancement, ui

#97 fix Countdown render condition
  client/src/components/Countdown/Countdown.tsx
Labels: fix

#101 Mise à jour des transitions de page
  client/src/components/MapButton/MapButton.tsx
  client/src/pages/Admin/Transition.tsx
  client/src/pages/Components/Transition.tsx
  client/src/pages/Finish/Transition.tsx
  client/src/pages/Home/Transition.tsx
  client/src/pages/Installation/Installation.tsx
  client/src/pages/Installation/ScrollMagicController.ts
  client/src/pages/Installation/Transition.tsx
  client/src/pages/Installation/installation.scss
  client/src/pages/Map/Transition.tsx
  client/src/pages/Twitter/Transition.tsx
Labels: refacto, ui

#107 Update/map
  client/src/components/map/mapgl.scss
  client/src/pages/Installation/Installation.tsx
  client/src/pages/Installation/installation.scss
Labels: ui

#112 Update/map
  client/src/assets/images/close_ico.svg
  client/src/assets/images/ico_walk.svg
  client/src/components/InformationsPanel/InformationsPanel.tsx
  client/src/components/InformationsPanel/informationsPanel.scss
  client/src/components/map/ProtoMap.tsx
Labels: enhancement, fix, map, ui

#119 Feature/splashscreen animation
  client/src/App.tsx
  client/src/assets/styles/app.scss
  client/src/components/Header/Header.tsx
  client/src/components/Header/header.scss
  client/src/components/ScrollIndication/ScrollIndication.tsx
  client/src/components/ScrollIndication/scroll-indication.scss
  client/src/components/SplashscreenAnimation/2019.svg
  client/src/components/SplashscreenAnimation/SplashscreenAnimation.tsx
  client/src/components/SplashscreenAnimation/splashscreen-animation.scss
  client/src/pages/Components/Components.tsx
  client/src/pages/Home/Home.tsx
  client/src/pages/Home/home.scss
  client/src/store/NavigationStore.ts
  client/src/utils/hooks.ts
Labels: component, enhancement, refacto, ui

#121 add TwitterGallery to installation page
  client/src/components/Button/button.scss
  client/src/components/TwitterGallery/TwitterGallery.tsx
  client/src/components/TwitterGallery/fakeData/alex.jpg
  client/src/components/TwitterGallery/fakeData/clara.jpg
  client/src/components/TwitterGallery/fakeData/index.ts
  client/src/components/TwitterGallery/fakeData/manon.jpg
  client/src/components/TwitterGallery/fakeData/robin.jpg
  client/src/pages/Installation/Installation.tsx
  client/src/pages/Installation/installation.scss
Labels: component, enhancement, ui

#124 Update/selected map icon
  client/src/components/map/MapController.ts
  client/src/components/map/ProtoMap.tsx
Labels: enhancement, map, refacto, ui

#126 fix blur animations on IOS
  client/src/components/SplashscreenAnimation/SplashscreenAnimation.tsx
  client/src/components/SplashscreenAnimation/splashscreen-animation.scss
  client/src/pages/Home/Home.tsx
  client/src/pages/Home/home.scss
  client/src/store/NavigationStore.ts
  client/src/utils/hooks.ts
Labels: fix, ui

#137 Ajout du slug pour les installations
  api/graphql/resolvers/installationList.js
  api/graphql/schema/index.graphql
  api/models/installation.js
  client/src/@types/index.d.ts
  client/src/components/InformationsPanel/InformationsPanel.tsx
  client/src/components/map/MapController.ts
  client/src/components/map/ProtoMap.tsx
  client/src/config/config.ts
  client/src/pages/Admin/Admin.tsx
  client/src/store/InstallationStore.ts
Labels: API MBGA, enhancement

#138 Page/menu
  client/src/components/MapButton/MapButton.tsx
  client/src/components/MapButton/mapButton.scss
  client/src/config/config.ts
  client/src/pages/Components/Transition.tsx
  client/src/pages/Map/Transition.tsx
  client/src/pages/Menu/Menu.tsx
  client/src/pages/Menu/Transition.tsx
  client/src/pages/Menu/menu.scss
  client/src/store/NavigationStore.ts
Labels: component, ui

#142 AudioPlayer + demo on component page
  client/public/assets/audio/sample1.mp3
  client/src/components/AudioPlayer/AudioPlayer.tsx
  client/src/components/AudioPlayer/audio-player.scss
  client/src/components/AudioPlayer/pause.svg
  client/src/components/AudioPlayer/play.svg
  client/src/pages/Components/Components.tsx
Labels: component, ui
